[package]
name = "abby_workshop"
authors = ["InaccurateTank (Tank#1623)"]
description = "A poorly assembled custom chatbot"
repository = "https://git.inaccuratetank.gay/inaccuratetank/abby_bot"
version = "0.2.2"
edition = "2021"

[dependencies]
poise = { version = "0.5" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
regex = { version = "1.7" }
time = { version = "0.3", features = ["formatting", "local-offset"] }
gumdrop = { version = "0.8" }
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls", "sqlite" ] }
serde = { version = "1" }
toml = { version = "0.7" }

[dev-dependencies]
brunch = "0.4"

[[bin]]
name = "abby_bot"
path = "src/bot/main.rs"

[lib]
name = "abby_utils"
path = "src/utils/lib.rs"

[[bench]]
name = "concat"
harness = false
