[package]
name = "abby_bot"
authors = ["inaccuratetank"]
description = "A poorly assembled custom chatbot"
repository = "https://git.inaccuratetank.gay/inaccuratetank/abby_bot"
version = "0.5.0"
edition = "2024"
publish = false

[dependencies]
poise = { version = "0.6" }
tokio = { version = "1.44", features = ["macros", "rt-multi-thread", "signal"] }
regex = { version = "1.11" }
time = { version = "0.3", features = ["formatting", "local-offset"] }
gumdrop = { version = "0.8" }
sqlx = { version = "0.8", features = [ "runtime-tokio-native-tls", "sqlite" ] }
serde = { version = "1.0" }
toml = { version = "0.8" }
tracing = { version = "0.1" }
tracing-error = { version = "0.2" }
tracing-subscriber = { version = "0.3" }
thiserror = { version = "2.0" }
color-eyre = { version = "0.6" }
